ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:
  # lint and format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
        args:
          - --fix
          - --show-fixes
      - id: ruff-format
