name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # Weekly Tuesday 6 AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 6 * * 2'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  initial_checks:
    name: Mandatory checks before CI
    runs-on: ubuntu-latest
    steps:
    - name: Check base branch
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3  # v9.0.0
      if: github.event_name == 'pull_request'
      with:
        script: |
          const allowed_basebranch = 'master';
          const pr = context.payload.pull_request;
          if (pr.base.ref !== allowed_basebranch) {
            core.setFailed(`PR opened against ${pr.base.ref}, not ${allowed_basebranch}`);
          } else {
            core.info(`PR opened correctly against ${allowed_basebranch}`);
          }

  tests:
    needs: initial_checks
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@e5af21e4ae37af089a73bb032e10b78b0e746174  # v3.0.1
    with:
      submodules: false
      coverage: ''
      envs: |
        - name: Lint with flake8
          linux: codestyle

        # Make sure that packaging will work
        - name: pep517 build
          linux: twine

        - name: Security audit
          linux: bandit

        - name: Check links
          linux: linkcheck

        - name: Python 3.10 with all dependencies
          linux: py310-test-alldeps
          posargs: -v --durations=0

        - name: Python 3.14 with dev dependencies
          linux: py314-test-devdeps
          posargs: -v --durations=0
