name: rc-testing

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rc_tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@e97344095b099e1d729fe97429078c9975921d8a  # v2.6.2
    with:
      setenv: |
        jref: "https://ssb.stsci.edu/trds_open/jref"
      submodules: false
      coverage: ''
      # TODO: Enable more OSes when possible.
      envs: |
        - name: Python 3.13 with pre-release
          linux: py313-test-predeps
          posargs: --remote-data -v
